### ISSUE TITLE
Question: Unable to print Simplified Chinese & Japanese characters (Epson TM-T82X)

### ISSUE THREAD

**Issue by zameschua** [receiptline/receiptline#17]
Hi receiptline team! I'm really loving what you guys are building so far.

I'm trying to print Simplified Chinese characters onto using `escpos` command on an Epson TM-T82X printer, but I'm getting gibberish instead.
For context, I'm using this in a React-Native app.
Also, it seems like Chinese printing is supported from the official docs for this specific printer model.
https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=364

## Chinese
![image](https://user-images.githubusercontent.com/18271085/133313732-455100b5-f161-48d3-ab59-89a439d890b7.png)

receiptline document
```
敏捷的棕色狐狸跳过懒狗
```
Printer config
```
const printer = {
  encoding: 'gb18030', // and cp936
  command: 'escpos',
};
```

## Japanese

I tried printing the Japanese sample afterwards to test it and there was a similar problem

![image](https://user-images.githubusercontent.com/18271085/133313608-6733dcba-a140-42a8-a387-fcb3c1e305ff.png)

receiptline document
```
敏捷的棕色狐狸跳过懒狗
```
Printer config
```
const printer = {
  encoding: 'cp932', // and shiftjis
  command: 'escpos',
};
```

## English

Here's the working English sample for comparison.

![image](https://user-images.githubusercontent.com/18271085/133313639-8a42b754-173c-4075-aebd-2d885f500fe0.png)

Thank you team in advance!

**Comment by zameschua** [comment]
Just an update from the printer supplier, the printer is able to support Chinese printing mode but there's a setting to enable multi-language font.

![Unknown-2](https://user-images.githubusercontent.com/18271085/133491848-76bb91f0-afee-4c62-8c48-64f55c355f9f.jpeg)


Just checking to see if you know a way to configure the setting via ESCPOS commands

**Comment by receiptline** [comment]
Thank you for using receiptline!

We don't have this model, so I tried to find a similar model.

`敏捷的棕色狐狸跳过懒狗` printed correctly with the following steps

- Change the multi-language font setting to Simplified Chinese with the utility.
- Set encoding to `gb18030` in the receiptline options.

I expected the command to set the multi-language font is GS ( E, but it was not listed in the ESC/POS command reference.

I think the manufacturer would like you to set it up with the utility.

**Comment by zameschua** [comment]
Hi @receiptline,
Thank you so much for taking a jab at the question! I'll be trying that out and let you know how it goes :)

**Comment by zameschua** [comment]
Just wanted to give an update, everything works after I configured the printer with the Epson utility.
I still hope to know if there's ever a way to configure it from ESC/POS commands if anyone ever finds out.

Thank you again!

**Comment by receiptline** [comment]
Hello!

I found an article by a user who tried to run receiptline with React Native. Sorry for the Japanese article.
https://qiita.com/yosim/items/4313da9a41fe2bb2744b

Thanks!
