### ISSUE TITLE
Question: How to send kick cash drawer command to printer?

### ISSUE THREAD

**Issue by zameschua** [receiptline/receiptline#18]
Hi @receiptline again!

Previously I would send the following command as bytes directly to kick the cash drawer:
`[0x1b, 0x70, 0x00, 0x19, 0xfa]`

According to the receiptline docs, the equivalent receiptine doc would be like this:
`{command:\x1b\x70\x00\x19\xfa}`

However, this doesn't successfully kick the cash drawer.
Am I missing something? Is there a better recommended way to do this?

PS: I'm testing on an Epson TM-T82X printer, using the following receiptline printer configuration
```
{
      encoding: 'gb18030', // Chinese
      command: 'escpos',
};
```

**Comment by receiptline** [comment]
Hello!

It is correct and will work.

```
{command:\x1b\x70\x00\x19\xfa}
```

The following is a syntax error and will be ignored.

```
{command:\x1b\x70\x00\x19\xfa} Kick!
```

In your program, please treat the string returned by receiptline as binary.

```js
Buffer.from(receiptline.transform(doc, options), 'binary');
```

```js
socket.write(receiptline.transform(doc, options), 'binary');
```

Thanks!

**Comment by zameschua** [comment]
Thank you so much @receiptline !
I managed to get it to work by sending a binary buffer over the TCP socket as suggested.

Keep up the good work on this project, loving it so far :)
