### ISSUE TITLE
Cannot line up images and something

### ISSUE THREAD

**Issue by eggplants** [receiptline/receiptline#2]
I can't put images and "images and text" side by side in designer:
```receiptline
|1
|{c:test;o:qrcode}
|2
|{c:test;o:qrcode}|
|3
{c:test;o:qrcode}|
|4
{c:test;o:qrcode}|{c:test;o:qrcode}
|5
{c:test;o:qrcode} | {c:test;o:qrcode}
|6
 a | {c:test;o:qrcode}
|7
 {c:test;o:qrcode} | a
```
![image](https://user-images.githubusercontent.com/42153744/87807293-0f42b880-c893-11ea-84b1-44c3fba1e753.png)

Is this a specification?

**Comment by eggplants** [comment]
http://www.ofsc.or.jp/receiptline_/readme_en.html
> The property is valid for lines with a single column.

Sorry, I skipped over it...

**Comment by receiptline** [comment]
To be able to do this we have to use page mode commands. However, due to compatibility issues with printer manufacturers, we are not supporting this at this time. Thanks.
