### ISSUE TITLE
Alignment Problem

### ISSUE THREAD

**Issue by ertugrulkutluer** [receiptline/receiptline#30]
Hi,

I am creating a design using the receiverline designer. However, alignment does not work properly. I am using Epson tm-t88vi thermal printer. I'm using "escpos" command.

This is my design.

`^^^^^^^^100

|"SHOP-NAME"|
|SHOP-ADDRESS-SHOULD-BE-HERE|
|SHOP-CITY|
|SHOP-COUNTRY|
      
|"ID | ORDER-ID|
|"DATE | ORDER-DATE|
|"TABLE | ORDER-TABLE|
|"SERVER | ORDER-SERVER|
|"TYPE | ORDER-TYPE|
      
- - - - - - - - - - - - - - - - - - - -
      
|"CUSTOMER
|CUSTOMER-NAME
      
- - - - - - - - - - - - - - - - - - - -
      
|X |NAME | AMOUNT|
|1 |Gazpacho (Medium Portion) | 15.65|

- - - - - - - - - - - - - - - - - - - -

|"Notes
|The quick brown fox jumps over the lazy dog.

- - - - - - - - - - - - - - - - - - - -

|SUBTOTAL | 30.50|
|TAX | 2.50|
|TOTAL | 33.00|`

and this is the result.

![WhatsApp Image 2022-08-15 at 12 08 11 PM (1)](https://user-images.githubusercontent.com/29006066/184608429-21586de3-b5ec-4c33-a479-b655dc888a7e.jpeg)

note: also divider not working properly. If I use the receiptline's own divider, emoji-like characters appear in the line.

**Comment by receiptline** [comment]
Hello!

I tried with TM-T88V and this problem did not occur.

Is the encoding of the writable stream `'binary'`?
If it is not `'binary'`, this may happen.

```js
const escpos = receiptline.transform(receiptmd, { command: 'escpos', cpl: 40 });

const socket = net.connect(port, host);
socket.write(escpos, 'binary');
```

```js
const escpos = receiptline.transform(receiptmd, { command: 'escpos', cpl: 40 });

const serialport = new SerialPort({ path: 'com1', baudRate: 9600 });
serialport.write(escpos, 'binary');
```

Thanks!

**Comment by ertugrulkutluer** [comment]
thank you for reply!
