### ISSUE TITLE
Small font with ESC/POS - CPL: 32 -> CPL:42

### ISSUE THREAD

**Issue by tc-maxx** [receiptline/receiptline#34]
Hello Receiptline,

I would like to use the ESC/POS printers integrated small-font.
With the small font I get 42 characters per line instead of 32 characters.
However, I would only use this small font for a certain part, the rest should remain CPL: 32 with the normal font.

With `{command:\x1b\x4d\x01}` I can activate the small font
when I'm done I switch back to normal font with `{command:\x1b\x4d\x00}`.

Now I have the problem that the text in the line is cut off after 32 characters.

Do you see a simple solution to change the CPL in between?

Thank you!

**Comment by receiptline** [comment]
Hello!
How about fixed column width?

```
{w:32; a:left}
|12345678901234567890123456789012
{w:42; x:\x1bM\x01}
|123456789012345678901234567890123456789012
{w:32; x:\x1bM\x00}
|12345678901234567890123456789012
```

Please set `cpl: 42`.

**Comment by tc-maxx** [comment]
So easy - I would not have thought that.

The printout now fits perfectly, but of course the lines with the small font in the SVG are now slightly overhanging.
![image](https://user-images.githubusercontent.com/17054281/197783306-04ce77d8-4a1c-4ba5-80c0-847ac68fcb8e.png)

Maybe you also have a solution to reduce the font of these lines?

Many Thanks!

**Comment by receiptline** [comment]
You are right. but there is no solution now.

Font B may have a different size or may not be installed on each model.
Also, the font size may vary by region even for the same model name.
To make receipt markdown an easy and convenient feature, we avoid chaotic Font B.

Thanks!

**Comment by tc-maxx** [comment]
Ok, thanks for your answer.

For me I made some small dirty changes in the code. With the new control character $, I downscale the font a bit in the output.

![image](https://user-images.githubusercontent.com/17054281/198051662-693af2d0-fc8f-4e43-a1fd-a35eb2e23575.png)

ciao
Max
