### ISSUE TITLE
Star MC-Print3 CloudPRNT Opening Cash Register

### ISSUE THREAD

**Issue by AChangXD** [receiptline/receiptline#35]
Good evening,

Is there an example on how to open the cash register via receiptline command for starsbcs? 
I tried Star's built in header for opening register, but it will only work if the specified content type is "text/plain". Even so, it will print a piece of blank paper that does effectively nothing.

Code: 
`const starPrinterRouter = express.Router();
const printer: Printer = {
  cpl: 48,
  encoding: 'cp437',
  upsideDown: true,
  spacing: true,
  command: 'starsbcs',
};
const order = () => `{width:*}
^^^Online Order
${new Date().toLocaleString('en')}
{width:4,*}
---
|^^^2|^^Hamburger
|    |Tomato, Onion, Meat sauce, Mayonnaise
|    |\`"~Mustard~
|^^^2|^^Clam chowder
|    |Oyster cracker
---
{code:1234567890; option:code128,2,72,hri}`;

let data = order();
    console.log(data);

    const command = receiptline.transform(data, printer);
    // remove ESC @ (command initialization) ESC GS a 0 (disable status transmission)
    const bin = Buffer.from(command.slice(6), 'binary');
    // const bin = Buffer.from(command, 'binary');
    console.log(bin);

    // res.end();
    res
      .set({
        'Content-Type': 'text/plain',
        'X-Star-CashDrawer': 'start',
      })
      .status(200)
      .send(bin);`

Thanks!

**Comment by receiptline** [comment]
Good evening.

Please try to embed the drawer kick command `BEL` (7).

```js
const order = () => `{width:*}
^^^Online Order
${new Date().toLocaleString('en')}
{width:4,*}
---
|^^^2|^^Hamburger
|    |Tomato, Onion, Meat sauce, Mayonnaise
|    |\`"~Mustard~
|^^^2|^^Clam chowder
|    |Oyster cracker
---
{code:1234567890; option:code128,2,72,hri}
{command:\x07}`;
```

Best regards.

**Comment by AChangXD** [comment]
Gotcha, the solution worked, thank you!
