### ISSUE TITLE
invisible image

### ISSUE THREAD

**Issue by zakaria-chahboun** [receiptline/receiptline#9]
Hi! Thanks for this amazing open source project!
I use https://receiptline.github.io/designer/ to design my bill as you can see bellow:

<img src="https://user-images.githubusercontent.com/18173275/127721858-d2822055-32a9-4316-a5f4-752cfb684c39.png" width="400px"/>

I downloaded the `receiptline.txt` and i check it with a text editor, It's Just Fine!
### But!
When i use it with node.js like that:
```js
  const doc = fs
    .readFileSync("/home/zaki/Downloads/receiptline.txt", { encoding: "utf-8" })
    .toString();

  const display = {
    cpl: 48,
    encoding: "cp437",
  };

  const svg = receiptline.transform(doc, display);
  fs.writeFileSync("/home/zaki/Documents/receiptline.svg", svg);
```
Its gives me this output:
<img src='https://user-images.githubusercontent.com/18173275/127722097-25258dd0-e43c-4afe-99c5-892cefdddd0e.png' width="400px" />

The rendered Svg doesn't have my image Logo!
I opened the SVG file with a text editor, It doesn't have the image *(base64)*!
It seems Like the `receiptline.transform` parser ignore it!
Why?

**Comment by receiptline** [comment]
Hello! Thanks for using receiptline.

`receiptline.txt` has a BOM (Byte Order Mark). So please try the following.

```js
  const doc = fs
    .readFileSync("/home/zaki/Downloads/receiptline.txt", { encoding: "utf-8" })
    .toString()
    .replace(/^\ufeff/, "");
```

**Comment by zakaria-chahboun** [comment]
Thanks!
